apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ps-testbed
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: testbed
  source:
    repoURL: https://github.com/imsosleepy/argocd.git
    targetRevision: main
    path: deploy
    helm:
      valueFiles:
        - test/values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      selfHeal: false
      prune: true
